-- Linguapolis v5: Supabase Auth + database + Row Level Security.
-- Run this file once in Supabase → SQL Editor.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Студент',
  email text,
  class_code text,
  avatar_id text not null default 'nova',
  role text not null default 'student' check (role in ('student', 'teacher', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safe migration for projects where the v4 schema was already installed.
alter table public.profiles add column if not exists avatar_id text not null default 'nova';

create table if not exists public.learner_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  character_id text not null,
  level integer not null default 1 check (level >= 1),
  xp integer not null default 0 check (xp >= 0),
  xp_next integer not null default 100 check (xp_next > 0),
  coins integer not null default 0 check (coins >= 0),
  confidence numeric(5,2) not null default 20 check (confidence between 0 and 100),
  vocabulary numeric(5,2) not null default 20 check (vocabulary between 0 and 100),
  fluency numeric(5,2) not null default 20 check (fluency between 0 and 100),
  accuracy numeric(5,2) not null default 20 check (accuracy between 0 and 100),
  completed_lessons integer not null default 0 check (completed_lessons >= 0),
  streak integer not null default 0 check (streak >= 0),
  last_lesson_date date,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, character_id)
);

create table if not exists public.answer_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  character_id text not null,
  lesson_id text not null,
  lesson_title text,
  prompt_index integer not null check (prompt_index >= 0),
  prompt_text text,
  task_text text,
  answer_text text not null check (char_length(answer_text) between 1 and 2000),
  relevance_score integer not null check (relevance_score between 0 and 100),
  vocabulary_score integer not null check (vocabulary_score between 0 and 100),
  structure_score integer not null check (structure_score between 0 and 100),
  fluency_score integer not null check (fluency_score between 0 and 100),
  overall_score integer not null check (overall_score between 0 and 100),
  target_used boolean not null default false,
  feedback jsonb not null default '[]'::jsonb,
  skill_gains jsonb not null default '{}'::jsonb,
  client_record_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.action_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  character_id text,
  session_id text,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  page text,
  app_version text,
  created_at timestamptz not null default now()
);

create index if not exists learner_profiles_user_idx on public.learner_profiles(user_id);
create index if not exists answer_attempts_user_created_idx on public.answer_attempts(user_id, created_at desc);
create index if not exists action_logs_user_created_idx on public.action_logs(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, email, class_code, avatar_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, 'Студент'), '@', 1)),
    new.email,
    nullif(new.raw_user_meta_data ->> 'class_code', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'avatar_id', ''), 'nova')
  )
  on conflict (id) do update set
    display_name = excluded.display_name,
    email = excluded.email,
    class_code = excluded.class_code,
    avatar_id = excluded.avatar_id,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of raw_user_meta_data, email on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('teacher', 'admin')
  );
$$;

alter table public.profiles enable row level security;
alter table public.learner_profiles enable row level security;
alter table public.answer_attempts enable row level security;
alter table public.action_logs enable row level security;

-- Students can read/update their own account. Teachers can read all students.
drop policy if exists "profiles_select_own_or_teacher" on public.profiles;
create policy "profiles_select_own_or_teacher" on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_teacher());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Progress belongs to the student; teachers can inspect and edit it.
drop policy if exists "learner_profiles_select" on public.learner_profiles;
create policy "learner_profiles_select" on public.learner_profiles
for select to authenticated
using (user_id = auth.uid() or public.is_teacher());

drop policy if exists "learner_profiles_insert" on public.learner_profiles;
create policy "learner_profiles_insert" on public.learner_profiles
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "learner_profiles_update" on public.learner_profiles;
create policy "learner_profiles_update" on public.learner_profiles
for update to authenticated
using (user_id = auth.uid() or public.is_teacher())
with check (user_id = auth.uid() or public.is_teacher());

-- Students see and create only their answers. Teachers see all answers.
drop policy if exists "answers_select" on public.answer_attempts;
create policy "answers_select" on public.answer_attempts
for select to authenticated
using (user_id = auth.uid() or public.is_teacher());

drop policy if exists "answers_insert" on public.answer_attempts;
create policy "answers_insert" on public.answer_attempts
for insert to authenticated
with check (user_id = auth.uid());

-- Logs follow the same ownership rule.
drop policy if exists "logs_select" on public.action_logs;
create policy "logs_select" on public.action_logs
for select to authenticated
using (user_id = auth.uid() or public.is_teacher());

drop policy if exists "logs_insert" on public.action_logs;
create policy "logs_insert" on public.action_logs
for insert to authenticated
with check (user_id = auth.uid());

-- After the teacher creates an account, promote it once with a query like:
-- update public.profiles set role = 'teacher' where email = 'teacher@example.com';
